(function(){
'use strict';
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localTime=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
let userId,key,draft,manual,revision=0,worker,editing=null,busy=false;
const fresh=()=>({version:1,demo:false,settings:{departure:localTime(),hours:'4'},jobs:[],offerDraft:{}});
function status(text){$('status').textContent=text;}
function formData(form){return Object.fromEntries([...new FormData(form)]);}
function writeForm(form,data){form.reset();for(const [name,value] of Object.entries(data||{})){const field=form.elements.namedItem(name);if(field){if(field.type==='checkbox')field.checked=value===true;else field.value=value??'';}}}
function save(){if(draft.demo){$('saveStatus').textContent='Sample only · Your own offers are kept separately.';return;}try{localStorage.setItem(key,JSON.stringify(draft));$('saveStatus').textContent='Saved on this device for your account.';}catch(e){$('saveStatus').textContent='Device storage unavailable. Keep this page open to retain your offers.';}}
function invalidate(message){revision++;worker?.terminate();worker=null;busy=false;$('build').disabled=false;$('build').textContent='Find my best day →';$('plan').replaceChildren();status(message||'Offers updated. Rebuild to see current estimates.');}
function render(){
 writeForm($('settings'),draft.settings);writeForm($('offerForm'),draft.offerDraft);editing=draft.jobs.some(j=>j.id===draft.offerDraft?.id)?draft.offerDraft.id:null;for(const form of [$('settings'),$('offerForm')])form.querySelectorAll('input,button').forEach(el=>el.disabled=!!draft.demo);$('addOffer').hidden=!!draft.demo;if(editing)$('addOffer').open=true;$('count').textContent=draft.jobs.length;
 $('modeNotice').classList.toggle('demo',!!draft.demo);$('modeNotice').textContent=draft.demo?'DEMO · Sample pay, miles and times. These packages are not real or bookable.':'Driver-entered offers · Live package feeds are not connected yet.';
 $('demo').hidden=!!draft.demo;$('manual').hidden=!draft.demo;
 $('jobList').innerHTML=draft.jobs.length?draft.jobs.map(j=>'<article class="job"><strong>'+escape(j.name||'Package offer')+'</strong><span>'+escape(j.pickup)+' → '+escape(j.delivery)+'</span><div class="muted">'+(j.committed?'Already accepted · ':'')+(j.canStack?'Stacking allowed by you':'Compare on its own')+' · '+(draft.demo?'DEMO':'Driver entered')+'</div><div class="actions"><b>'+money(Number(j.pay)||0)+'</b><div><button type="button" '+(draft.demo?'disabled ':'')+'data-edit="'+escape(j.id)+'">Edit</button> <button type="button" data-remove="'+escape(j.id)+'">Remove</button></div></div></article>').join(''):'<p class="muted">No offers yet. Add an offer awaiting pickup, or try a sample day.</p>';
 save();
}
function demoDraft(){return {version:1,demo:true,settings:{start:'Riverdale, GA',home:'Riverdale, GA',departure:localTime(),hours:'4',mpg:'25',gas:'3.50',wear:'0.20',payload:'200',volume:'8',target:'20',overhead:'0'},jobs:[{id:'sample-a',name:'Sample auto parts',pickup:'East Point, GA',delivery:'Atlanta, GA',pay:32,weight:10,volume:1,service:5,canStack:true},{id:'sample-b',name:'Sample retail package',pickup:'Forest Park, GA',delivery:'Atlanta, GA',pay:26,weight:8,volume:1,service:5,canStack:true},{id:'sample-c',name:'Sample long detour',pickup:'Macon, GA',delivery:'Atlanta, GA',pay:18,weight:5,volume:1,service:5,canStack:true}],offerDraft:{}};}
function demoMatrix(locations){const points={'Riverdale, GA':[0,0],'East Point, GA':[0,8],'Atlanta, GA':[0,16],'Forest Park, GA':[4,4],'Macon, GA':[65,-50]};return locations.map(a=>locations.map(b=>{const p=points[a],q=points[b];if(!p||!q)throw Error('The demo uses sample cities. Switch to My offers to plan your own addresses.');const miles=Math.hypot(p[0]-q[0],p[1]-q[1]);return {miles,minutes:miles*2.4};}));}
function solve(snapshot,matrix){return new Promise((resolve,reject)=>{const w=new Worker('car-worker.js');worker=w;const timer=setTimeout(()=>{w.terminate();reject(Error('Planning took too long. Your offers are saved. Try fewer packages or retry.'));},18000);w.onmessage=e=>{clearTimeout(timer);w.terminate();worker=null;e.data.error?reject(Error(e.data.error)):resolve(e.data.result);};w.onerror=()=>{clearTimeout(timer);w.terminate();worker=null;reject(Error('Planner could not start. Refresh and retry; your offers are saved.'));};w.postMessage({draft:snapshot,matrix});});}
function routeResult(result){
 if(!result.best){status(result.issues[0]);return;}
 const r=result.best;status(r.meetsGoal?'This combination meets your estimated hourly goal.':'Below your goal. Review the costs before accepting more work.');
 const time=v=>new Date(v*60000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
 $('plan').innerHTML='<div class="notice'+(draft.demo?' demo':'')+'"><b>'+(r.meetsGoal?'Best of the compared plans':'Best available preview')+'</b><br>'+r.loads.length+' package'+(r.loads.length===1?'':'s')+' · '+result.compared+' feasible combinations compared</div><div class="metrics"><div class="metric"><span>Estimated after vehicle costs</span><b>'+money(r.net)+'</b></div><div class="metric"><span>Per total working hour</span><b>'+money(r.hourly)+'</b></div><div class="metric"><span>Complete trip, including home</span><b>'+r.miles.toFixed(1)+' mi</b></div><div class="metric"><span>Driving + waits + service</span><b>'+r.hours.toFixed(1)+' hr</b></div></div><p class="muted">'+(draft.demo?'DEMO: all pay and routing figures are simulated.':'Road estimates use general roads without live traffic. Recheck provider deadlines and availability.')+' Before tax; fixed ownership/insurance costs are not included.</p><details><summary>See the money breakdown</summary><p>Driver pay '+money(r.totalPay)+' − fuel '+money(r.fuelCost)+' − wear '+money(r.wearCost)+' − fees, tolls & parking '+money(r.fees)+' = '+money(r.net)+'.</p><p>'+escape(r.loads.map(l=>l.name).join(' + '))+'</p><p>Uses '+escape(draft.settings.mpg||25)+' MPG, $'+escape(draft.settings.gas||3.5)+'/gal, $'+escape(draft.settings.wear||.2)+'/mi wear. Empty settings use the displayed assumptions.</p></details><details open><summary>Pickup & delivery order</summary><ol><li>Start · '+escape(draft.settings.start)+'</li>'+r.events.map(e=>'<li><b>'+(e.type==='pickup'?'Pick up':e.type==='drop'?'Deliver':'Finish')+'</b> · '+escape(e.location)+'<br><small>'+time(e.arrivalMinutes)+(e.load?' · '+escape(e.load.name):'')+'</small></li>').join('')+'</ol></details><p class="muted">'+(r.capacityAssumed?'Car capacity uses planning assumptions. ':'')+(!r.capacityVerified?'Some package measurements are missing. ':'')+'Volume does not prove physical fit; check package dimensions. '+(r.windowDetailsMissing?'Some provider deadlines are missing. ':'')+'Confirm each offer with its provider. Nothing is booked here.</p>';
 if(result.alternatives.length){const d=document.createElement('details');d.innerHTML='<summary>Compare other combinations</summary>'+result.alternatives.map(a=>'<p>'+escape(a.loads.map(l=>l.name).join(' + '))+'<br><b>'+money(a.net)+'</b> after vehicle costs · '+money(a.hourly)+'/hr · '+a.miles.toFixed(1)+' mi</p>').join('');$('plan').append(d);}
 const omitted=draft.jobs.filter(j=>!r.loads.some(l=>l.providerLoadId===j.id));if(omitted.length){const p=document.createElement('p');p.className='muted';p.textContent='Not in this recommendation: '+omitted.map(j=>j.name||'Package offer').join(', ')+'. Your offers are still saved.';$('plan').append(p);}
}
async function build(){
 if(busy)return;const token=++revision,snapshot=structuredClone(draft);busy=true;$('build').disabled=true;$('build').textContent='Comparing your day…';$('plan').replaceChildren();status('Checking roads, package combinations and the trip home…');$('results').scrollIntoView({block:'start'});
 try{const prepared=MileCountCarPlanner.prepare(snapshot);let matrix;if(snapshot.demo)matrix=demoMatrix(prepared.problem.locations);else{const route=await getMileCountGeneralRoadMatrix(prepared.problem.locations);matrix=route.matrix;}if(token!==revision)return;const result=await solve(snapshot,matrix);if(token!==revision)return;routeResult(result);}
 catch(e){if(token===revision)status(e.message||'Unable to compare this day. Your offers are saved; please retry.');}
 finally{if(token===revision){busy=false;$('build').disabled=false;$('build').textContent='Find my best day →';}}
}
async function init(){
 let session;try{session=await Promise.race([MileCountCloud.session(),new Promise(resolve=>setTimeout(()=>resolve(null),10000))]);}catch(e){}
 if(!session?.user?.id){$('gateStatus').textContent='Sign in with your existing MileCount account to save and compare your offers.';return;}
 userId=session.user.id;key='milecount:car:v1:'+userId;try{const stored=JSON.parse(localStorage.getItem(key)||'null');draft=stored?.version===1&&Array.isArray(stored.jobs)&&stored.settings?stored:fresh();draft.demo=false;}catch(e){draft=fresh();}
 $('gate').hidden=true;$('workspace').hidden=false;render();window.MileCountConnections?.init(userId);
 $('settings').addEventListener('submit',e=>e.preventDefault());$('settings').addEventListener('input',()=>{draft.settings=formData($('settings'));invalidate();save();});
 $('offerForm').addEventListener('input',()=>{draft.offerDraft={...formData($('offerForm')),id:editing,canStack:$('offerForm').elements.canStack.checked,committed:$('offerForm').elements.committed.checked};save();});
 $('offerForm').addEventListener('submit',e=>{e.preventDefault();if(!editing&&draft.jobs.length>=5){status('Compare up to five offers. Remove one before adding another.');return;}
 const j={...formData($('offerForm')),id:editing||crypto.randomUUID(),canStack:$('offerForm').elements.canStack.checked,committed:$('offerForm').elements.committed.checked};
 if(editing)draft.jobs=draft.jobs.map(x=>x.id===editing?j:x);else draft.jobs.push(j);editing=null;draft.offerDraft={};invalidate('Offer saved. Ready to compare your day.');render();$('addOffer').open=false;
 });
 $('jobList').addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),remove=e.target.closest('[data-remove]');if(edit){editing=edit.dataset.edit;draft.offerDraft={...draft.jobs.find(j=>j.id===editing)};save();writeForm($('offerForm'),draft.offerDraft);$('addOffer').open=true;$('addOffer').scrollIntoView();}if(remove){draft.jobs=draft.jobs.filter(j=>j.id!==remove.dataset.remove);if(editing===remove.dataset.remove){editing=null;draft.offerDraft={};}invalidate('Removed from this plan. This does not cancel a provider booking.');render();}});
 $('demo').onclick=()=>{manual=draft;draft=demoDraft();editing=null;invalidate();render();build();};$('manual').onclick=()=>{draft=manual||fresh();editing=null;invalidate('Your own saved offers are restored.');render();};$('build').onclick=build;
 addEventListener('storage',e=>{if(e.key==='milecount_supabase_session'){location.reload();}else if(e.key===key){invalidate('This plan changed in another tab. Reload to use the latest saved offers.');$('build').disabled=true;$('workspace').querySelectorAll('input,button').forEach(el=>el.disabled=true);}});
}
init();
})();
