const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
(async()=>{const root=process.cwd(),server=http.createServer((req,res)=>{try{const file=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',({'html':'text/html','js':'application/javascript','css':'text/css'})[file.split('.').at(-1)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE,args:['--no-sandbox'],headless:true});
try{const ctx=await browser.newContext({viewport:{width:390,height:844}});let user='car-driver-a',roadFail=false;const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await ctx.addInitScript(()=>localStorage.setItem('milecount_supabase_session',JSON.stringify({access_token:'car-qa-only'})));
await page.route('**/*',async route=>{const u=route.request().url();if(u.startsWith(base))return route.continue();const json=(x,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(x)});if(u.includes('/auth/v1/user'))return json({id:user});if(u.includes('nominatim'))return json([{lat:'33.7',lon:'-84.3',display_name:'QA address'}]);if(u.includes('/table/')){if(roadFail)return json({},503);const n=new URL(u).pathname.split('/').at(-1).split(';').length;return json({code:'Ok',distances:Array.from({length:n},(_,a)=>Array.from({length:n},(_,b)=>Math.abs(a-b)*1609.344)),durations:Array.from({length:n},(_,a)=>Array.from({length:n},(_,b)=>Math.abs(a-b)*120))});}return json({},503);});
await page.goto(base+'/car.html');await page.locator('#workspace').waitFor({state:'visible'});
await page.locator('#settings [name=start]').fill('Riverdale, GA');await page.reload();await page.locator('#workspace').waitFor({state:'visible'});assert.equal(await page.locator('[name=start]').inputValue(),'Riverdale, GA','Partial form persists');
await page.locator('#demo').click();await page.waitForFunction(()=>document.querySelector('#plan .metrics'),null,{timeout:22000}).catch(async e=>{throw Error((await page.locator('#status').textContent())+' | '+errors.join('; ')+' | '+e.message)});assert.match(await page.locator('#modeNotice').textContent(),/DEMO/);assert.match(await page.locator('#plan').textContent(),/sample|simulated/i);assert.equal(await page.locator('#jobList .job').count(),3);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
if(process.env.QA_SCREENSHOT_DIR){fs.mkdirSync(process.env.QA_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.QA_SCREENSHOT_DIR,'car-demo-mobile.png'),fullPage:true});}
await page.locator('#manual').click();assert.equal(await page.locator('#jobList .job').count(),0);assert.equal(await page.locator('[name=start]').inputValue(),'Riverdale, GA');
await page.locator('#addOffer summary').first().click();await page.locator('#offerForm [name=name]').fill('<img src=x onerror=alert(1)>');await page.locator('#offerForm [name=pay]').fill('32');await page.locator('#offerForm [name=pickup]').fill('East Point, GA');await page.locator('#offerForm [name=delivery]').fill('Atlanta, GA');await page.locator('#offerForm button').click();assert.equal(await page.locator('#jobList img').count(),0,'No HTML injection');
await page.locator('#build').click();await page.waitForFunction(()=>document.querySelector('#plan .metrics'));assert.match(await page.locator('#plan').textContent(),/measurements are missing/);assert(!/Not in this recommendation/.test(await page.locator('#plan').textContent()));
await page.locator('[name=hours]').fill('5');assert.equal(await page.locator('#plan .metrics').count(),0,'Old results invalidated');roadFail=true;await page.locator('#build').click();await page.waitForFunction(()=>!document.querySelector('#build').disabled);assert.match(await page.locator('#status').textContent(),/unavailable/i);assert.equal(await page.locator('#jobList .job').count(),1);roadFail=false;await page.locator('#build').click();await page.waitForFunction(()=>document.querySelector('#plan .metrics'));
await page.locator('[data-edit]').click();await page.locator('#offerForm [name=pay]').fill('40');await page.reload();await page.locator('#workspace').waitFor({state:'visible'});assert.equal(await page.locator('#offerForm [name=pay]').inputValue(),'40','In-progress edit persists');await page.locator('#offerForm button').click();assert.equal(await page.locator('#jobList .job').count(),1,'Reloaded edit updates original offer');assert.match(await page.locator('#jobList').textContent(),/40.00/);await page.reload();await page.locator('#workspace').waitFor({state:'visible'});assert.equal(await page.locator('#jobList .job').count(),1);assert.equal(await page.locator('#plan .metrics').count(),0,'Never resurrect stale route');
user='car-driver-b';await page.reload();await page.locator('#workspace').waitFor({state:'visible'});assert.equal(await page.locator('#jobList .job').count(),0,'No cross-account offers');assert.equal(await page.locator('[name=start]').inputValue(),'');assert.deepEqual(errors,[]);await ctx.close();
const signedout=await browser.newContext(),p=await signedout.newPage();await p.goto(base+'/car.html');await p.locator('#gate').waitFor();assert(await p.locator('#workspace').isHidden());await signedout.close();console.log('PASS mobile car demo, partial autosave, account isolation, real offer editing, routing failure/retry, XSS and stale-result invalidation');
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1);});
