const assert=require('node:assert/strict'),{prepare,compare}=require('../car-planner.js');
const settings={start:'Home, GA',home:'Home, GA',departure:'2026-10-03T08:00',hours:4,mpg:25,gas:3.5,wear:.2,payload:50,volume:5,target:10,overhead:3};
const jobs=[{id:'a',name:'Parts',pickup:'A, GA',delivery:'C, GA',pay:30,weight:10,volume:1,service:5,canStack:true},{id:'b',name:'Retail',pickup:'B, GA',delivery:'C, GA',pay:25,weight:10,volume:1,service:5,canStack:true},{id:'c',name:'Poor detour',pickup:'Far, GA',delivery:'C, GA',pay:1,weight:5,volume:1,service:5,canStack:true}];
const coords={'Home, GA':0,'A, GA':1,'B, GA':2,'C, GA':3,'Far, GA':60};
const matrix=d=>prepare(d).problem.locations.map(a=>prepare(d).problem.locations.map(b=>({miles:Math.abs(coords[a]-coords[b]),minutes:Math.abs(coords[a]-coords[b])*2})));
let d={settings,jobs},r=compare(d,matrix(d));assert(r.best);assert.equal(r.best.loads.length,2);assert.equal(r.best.totalPay,55);assert.equal(r.best.routeStops.at(-1),'Home, GA');assert.equal(r.best.miles,6);assert.equal(r.best.hours,32/60);assert(Math.abs(r.best.net-(55-6*.14-6*.2-3))<1e-8);assert(r.best.events.findIndex(e=>e.load?.providerLoadId==='a'&&e.type==='pickup')<r.best.events.findIndex(e=>e.load?.providerLoadId==='a'&&e.type==='drop'));
console.log('CAR evidence: two compatible offers, $55 projected, 6 total miles / 32 minutes / $49.96 after variable costs; low-pay 120-mile detour excluded.');
d={settings,jobs:jobs.slice(0,2).map(j=>({...j,canStack:false}))};assert.equal(compare(d,matrix(d)).best.loads.length,1,'Unapproved combinations are excluded');
d={settings,jobs:[{...jobs[0],canStack:false,committed:true},{...jobs[1],canStack:false,committed:true}]};assert.equal(compare(d,matrix(d)).best,null,'Never discard an accepted offer to produce a plan');
d={settings,jobs:[{...jobs[0],weight:51}]};assert.equal(compare(d,matrix(d)).best,null);
d={settings,jobs:[{...jobs[0],volume:6}]};assert.equal(compare(d,matrix(d)).best,null);
d={settings,jobs:[{...jobs[0],deliverBy:'2026-10-03T08:08'}]};assert.equal(compare(d,matrix(d)).best,null,'Service completion must meet deadline');
d={settings:{...settings,hours:.25},jobs:[jobs[0]]};assert.equal(compare(d,matrix(d)).best,null,'Home leg counts toward shift');
d={settings,jobs:[{...jobs[0],delivery:'C, AL'}]};assert.throws(()=>prepare(d),/stay in GA/);
d={settings,jobs:[{...jobs[0],pay:0}]};r=compare(d,matrix(d));assert(r.best.net<0);assert.equal(r.best.meetsGoal,false);
d={settings,jobs:[{...jobs[0],weight:'',volume:''}]};assert.equal(compare(d,matrix(d)).best.capacityVerified,false);
d={settings:{...settings,payload:'',volume:''},jobs:[jobs[0]]};assert(compare(d,matrix(d)).best.capacityAssumed);
d={settings,jobs:[jobs[0]]};const broken=matrix(d);broken[0][1]=null;assert.equal(compare(d,broken).best,null,'No road means no fabricated route');
assert.throws(()=>prepare({settings:{...settings,mpg:-1},jobs}),/MPG/);assert.throws(()=>prepare({settings,jobs:[...jobs,jobs[0]]}),/unique/);
console.log('PASS car-package economics, deadlines, capacity, commitments, source permission and no-route cases');
